### ISSUE TITLE
crop viewport axis labels

### ISSUE THREAD

**Issue by olarosling** [vizabi/vizabi#103]
**WARNING!**
**read the discussion below before attempting to fix**

...

When zoomed in, the axis labeling should not continue outside the current y-axis-min and x-axis-min. Don-t show bubbles outside the axis either
![image](https://cloud.githubusercontent.com/assets/496398/7145535/430b184c-e2ed-11e4-9086-3b13057c0ef8.png)

**Comment by angieskazka** [comment]
how about y-axis-max and x-axis-max?

**Comment by arthurcamara1** [comment]
I think it shouldn't be simply masked out, otherwise we get these weird cases where numbers are not entirely visible:

![screen shot 2015-04-16 at 2 28 33 pm](https://cloud.githubusercontent.com/assets/3584238/7180779/2b280de4-e445-11e4-9938-da013cf19913.png)

Instead, I think you should not draw the axis line outside the min x and y, neither the ticks that fall outside.

There needs to be a max x and y as well. In summary, I guess the axis line should never change sizes, only ticks moving according to zoom and bubbles as well.

**Comment by arthurcamara1** [comment]
Sketched this to be more clear:

![bubblefixes](https://cloud.githubusercontent.com/assets/3584238/7180979/f0d5f618-e446-11e4-9010-883bede037c4.png)

**Comment by angieskazka** [comment]
Thanks for comments, @arthurcamara1 

Blue was easier to do then not to (so i removed a bit of code and it's done). But now i don't like using the screen's real estate. I have a design proposal on how to address it, but let's take it later.

Red is debatable, left it as it is for now

Green is complex and can wait until the "enhancement" flag here

**Comment by angieskazka** [comment]
This issue can not be resolved by adjusting constants. It's a deeper problem concerning the interplay between label positioning engine axisWithLabelPicker.js and SVG within SVG axis containers needed for zoom feature of the bubble chart. Solution requires much understanding of all sides

**Comment by angieskazka** [comment]
Fixed for default zoom. The other zoom values can stay for a while until we have time to deal with it

**Comment by angieskazka** [comment]
current behavior after changes in 30ee95b 

![msevnvh5xu](https://cloud.githubusercontent.com/assets/3648190/19532291/635b7198-963b-11e6-8110-ae4542576a15.gif)
