### ISSUE TITLE
Detailed ready events needed

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#106]
After changing "entities:show" we fire change event
But we also want to know when is the data ready for "entities:show". Such event is missing now
Also "ready after first load" is needed to run a full startup sequence of a tool

this replaces an old #60

**Comment by arthurcamara1** [comment]
`readyOnce` is fixed by 197d985d993673c37618fda0025d15f1015228b8 :smile:

**Comment by arthurcamara1** [comment]
And I just noticed something @angieskazka, the other one is ready. You can't bind to `entities:show` because that is not a hook, it doesn't contain data. You can, however, bind it to a specific hook.

Example:

```javascript
...
"ready:marker:label": function() {
    //triggered when this specific hook/model with the data got ready (finished loading data)
    console.log(_this.model.marker.label.getItems());
},
"ready": function(evt) {
    //triggered when all models of this component are ready
}
...
```

**Comment by angieskazka** [comment]
Seems like it's not that easy. The suggested above doesn't work, i tried

**Comment by arthurcamara1** [comment]
So, `ready:marker:label` does work, but it only guarantees that label is ready, nothing else, which means that in that function you cannot expect anything else to be ready other than that. If you do, it breaks.

As discussed, let's keep `ready` for when everything is ready and put this on hold, since it's an optimization, basically.
