### ISSUE TITLE
Entities filtered by multi-typing of subDimension

### ISSUE THREAD

**Issue by olarosling** [vizabi/vizabi#1252]
To ensure we are supporting multi-typing of entities, I'd like to see a bubble chart of the geos that are is.un_state = TRUE in this file.
The graph models so far seem to define geos as being countries, but the same geo should be able to also be a un_state (or not) and I want to make sure this is part of the model.

**Comment by jheeffer** [comment]
We have to come up with a new contract between Vizabi and the readers for this. 

What is the complexity of queries we want to support?

1. Just where `geo.subdim = x OR geo.subdim = y`. This could use the current format in Vizabi `geo.subdim: ["x","y"]`
2. Support both logical operators. `(geo.subdim = x AND geo.subdim = y) OR geo.subdim = z`
This might be useful for e.g. getting only city states `(geo.subdim = 'country' AND geo.subdim = 'city')`. This would need a different way of encoding this to JSON in Vizabi config. 

There's one more problem in general and with the above. CSV's generated from DDF now have one column for subdimension. (like this one, geo.cat: https://github.com/Gapminder/vizabi/blob/develop/.data/waffles/basic-indicators-geo-properties.csv). If we want them to support the multidimensionality in DDF (geo is city ánd country ánd un_state), there should be a true/false column for every subdimension (so `bool geo.is.country`, `bool geo.is.un_state` etc.). Having these columns ánd the above `geo.subdim = ['x', 'y']`, means the csv reader has to be smart about translating Vizabi `geo.subdim =` to querying the different true/false columns. So the CSV reader would not be a generic csv-reader anymore. 

To prevent having this kind of specificity for DDF'ish csvs, we can directly mention the columns in vizabi. `'geo.is.country': true, 'geo.is.city': true`. Then waffle reader/server should be smart to recognise the '.is.' as a request for entities belonging to a certain subdimension.

This is all presuming the same config should work for different readers. Maybe that's a far reach anyway in the end because DDF/waffle server can server more complex data which a csv just can't handle. 

So. Long story short:
1. In general: What is the complexity of subdimension queries we want to support? Just OR or both AND and OR?
2. On CSV-reader: Do we want csv's from DDF supporting multidimensionality? If not, we can stay with `geo.subdim: 'x','y']`. In csv reader would just look for a column geo.subdim. If we do, do we make csv smart or dumb about subdimensions?

**Comment by valorkin** [comment]
OR(one of conditions should be satisfied) is already supported `geo.subdim = x OR geo.subdim = y` equals to `geo.subdim = x,y`
AND(all conditions should be satisfied) not implemented, could be encoded simply as 
`[x,y,'AND',z]` -> `(x or y) and z`

**Comment by valorkin** [comment]
actually all parts could be encoded via `str.split(' ')` and reversed via `arr.join(' ')`
much better than stringify object

**Comment by jheeffer** [comment]
On the one hand, yes, on the other, mixing logical operators and values seems... wrong?

would we have multi dimensional arrays for brackets?
`(x AND y) OR (y AND z)` = `[[x, 'AND', y],'OR',['y', 'AND', 'z']]`

**Comment by valorkin** [comment]
1. we don't have now string like queries, only object like by vizabi :)
2. `(x AND y) OR (y AND z)` -> `["(x", "AND", "y)", "OR", "(y", "AND", "z)"]`
in object like  `(x AND y) OR (y AND z)` -> `{where: {geo: {
and: [
or: [x,y],
or: [y,z]
]
}}}`

**Comment by olarosling** [comment]
Me and Arthur decided to use OR as default. If nothing said, its OR: 
I prefer seeing this in states etc,   {geo: [x,y]}   instead of: {geo: { or: [x,y] } }
where the or looks strange.
If the query should be explicit or needs to do something more complex : then wee need the explicit (x AND y) OR (y AND z) -> ["(x", "AND", "y)", "OR", "(y", "AND", "z)"] in object like (x AND y) OR (y AND z) -> {where: {geo: { and: [ or: [x,y], or: [y,z] ] }}}

**Comment by valorkin** [comment]
what you have decided sound more like `in` operator
`when x in [1,2,3]`
but ok, or is by default

**Comment by jheeffer** [comment]
Alright, that sounds fair so:
Default: `dimension(.subdim): [x,y,z]` -> or (if array)

But the complex one needs some fine tuning. With the previous encoding this query would be hard to encode: `(x or y) and (y or (z and m)) and m`. I propose:
```
dimension(.subdim): { 
    and: {
        or: {
            val: x,
            val: y
        }, 
        or: {
            val: y,
            and: {
                val: z,
                val: m
            }
        },
        val: m
    }
}
```
This gives a unambiguous and coherent way to encode, with only objects. The `val:` might seem a bit unnecessary, but it's needed to make this kind of nesting possible.

**Comment by jheeffer** [comment]
Second, do we prefer

1 `{ geo.subdim: ['country', 'city'] }`

or 

2 `{ geo.is.country: true, geo.is.city: true }`

See write up above for implications (i.e. 1 will not work with ddf in *normal* csv-reader)

**Comment by angieskazka** [comment]
i prefer 1, as it looks like enumeration within one operator. 2 looks like two operators

**Comment by jheeffer** [comment]
https://gist.github.com/jheeffer/6ba717f67fe31ee37a1e

**Comment by angieskazka** [comment]
the original post was about entities multityping only

> To ensure we are supporting multi-typing of entities, I'd like to see a bubble chart of the geos that are is.un_state = TRUE in this file.
> The graph models so far seem to define geos as being countries, but the same geo should be able to also be a un_state (or not) and I want to make sure this is part of the model.

we have tried this with the IKEA dataset: geos are countries and cities, and we could request either one or both. CSV tables were containing countries and cities only, with geo only being set as a common entity domain for both. 

then the discussion went on do DDFQL specification and moved over to google docs and gist.githb…. so i suggest we close it =)
