### ISSUE TITLE
Confusing white bubble color. Let's communicate the exact value / missing data in the color legend

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1389]
**SEVERITY:**  Minor

**MODULE:**  Bubble chart

**Platform:**  
* Windows 7 / Firefox  44.0
* Windows 7 / Chrome 48.0

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools 
2)	Bubble Chart will be loaded.
3)	Click color icon
4)	Click drop down and select “Life expectancy” 
5)	Note that some bubbles have white background instead of having color according to color scale. 

**ACTUAL RESULTS:**
Some bubbles have white background instead of having color according to color scale. 

**EXPECTED RESULTS:**
Bubbles color should be according to selected color scale

**SCREENSHOT:**

![v0 12 8_06](https://cloud.githubusercontent.com/assets/9950837/13487254/293b2ee2-e13a-11e5-8365-64ec783f48b7.png)

**Comment by sergey-filipenko** [comment]
@angieskazka Should I add color property to bubble visibility condition?

**Comment by sergey-filipenko** [comment]
![image](https://cloud.githubusercontent.com/assets/3844375/13526536/21f0f3f6-e211-11e5-8250-89f87348dfd8.png)
also this problem exists

**Comment by angieskazka** [comment]
@sergey-filipenko 
1. no, it's good to show that we have no data, at least we can show X Y S of the bubble
2. thanks for pointing out the difference. i added a temporary hack so you can find Monaco in the list

**Comment by angieskazka** [comment]
let's improve the vertical text on bubble chart and color legend

vertical text `Size: Population, Color: World Region` should only be visible in small and medium profile (because on large it duplicates the functionality of the sidebar)

* when hovering many bubbles: do nothing (this is possible if, for example, all Europe bubbles are hovered via the minimap)
* when hovering 1 bubble (small-medium profile): change the vertical text to show the formatted data values + units. See how it's done in bubble map: `Size: 9.5 B people, Color: Europe` (map hides Color: region because it's a map). Write "No data" if it has no data
* when hovering 1 bubble (large profile), data exists: do nothing for now. we will handle it later
* when hovering 1 bubble (large profile), data is missing for color: add an overlay on top of color legend (the part below color selector) and write "No data" on top of it

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1709
