### ISSUE TITLE
The Y axis values got disturbed when zoom with transition

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1556]
**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:** Windows 7 / Firefox 45.0 or Mac OS / Chrome

**Realease:** V0.13.4

**STEPS TO REPRODUCE:**
1) Navigate to the URL : http://tools-stage.gapminderdev.org/
2) Bubble Chart will be loaded.
*you may also need to select "Income per person" for the Y axis to get pivoted axis labels*
3) Click on options 
4) Click on buttons /zoom
5) Click on 100% button 

**ACTUAL RESULTS:**
The Y axis values got disturbed when user clicks on 100% button 

**EXPECTED RESULTS:**
The Y axis values should not get disturbed 

**NOTE:** The functionality is working fine in chrome 

**SCREENSHOT:**

![yaxis 24](https://cloud.githubusercontent.com/assets/9950837/14011453/90313e70-f1c0-11e5-8fb6-62298ad9ac68.png)

**Comment by angieskazka** [comment]
Only happens when Y axis tick labels are pivoted (vertical)
Only happens when zoom event (+ or 100%) has animation ≠ 0
Only happens when zoom "go" method is calling axis update

Some discovered event sequence:
Press button, bubblechart captures event
Zoom "go" event is produced (bubblechart-panzoom: L350)
Axis calls update, labels are re-positioned correctly (see d3.axisWithLabelPicker: L 62 - 83)
Every axis label has attributes like `dy = 0, x = 0, y = -9` because the above
Some stuff happens inside d3.js
...
Laspass, adblock, etc DOM parsers are called
...
More stuff happens inside d3.js (likely some remaining animation frames)

Nothing is being called again in d3.axisWithLabelPicker.js
Axis are now broken
Every axis label has attributes like `dy = 0, x = -9, y = 0`

**Comment by angieskazka** [comment]
the Y values got fixed by the #1915 (5a2d4f481fbb3bc05af2b1d9d237a75e45f0e821)
