### ISSUE TITLE
Bubblemap: copy gapminder world behaviour for earthquake deaths

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#1661]
Make this:
http://www.gapminder.org/tools/map#_state_marker_size_which=earthquake%2F_deaths%2F_annual%2F_number

look more like this:

http://www.gapminder.org/world/#$majorMode=map$is;shi=t;ly=2003;lb=f;il=t;fs=11;al=30;stl=f;st=f;nsl=t;se=t$wst;tts=C$ts;sp=2.37806451612904;ti=1970$zpv;v=0$inc_x;mmid=XCOORDS;iid=phAwcNAVuyj1jiMAkmq1iMg;by=const$inc_y;mmid=YCOORDS;iid=phAwcNAVuyj0NpF2PTov2Cw;by=const$inc_s;uniValue=8.21;iid=rvbbs7uxQc7swJ4RR2BcQfA;by=ind$inc_c;uniValue=255;gid=CATID0;by=grp$map_s;sma=94;smi=2.65$cd;bd=0$inds=;example=65

I.e. no disappearing bubbles and bigger/smaller animation

no priority, but good to have on backlog.

Data has all years filled up with zeroes to get this behaviour:
https://github.com/semio/ddf--gapminder--gapminder_world/blob/master/output/ddf/ddf--datapoints--earthquake_deaths_annual_number--by--geo--time.csv

might very well be js falsey values/`0 != null` kind of thing.

**Comment by angieskazka** [comment]
You are comparing it with size: "children per woman" graph but it's not correct because children are interpolatable, while incidents aren't. 

Bubbles will be either disappearing if data is missing, because what would you otherwise do with missing data? 
Or they are going to be animating (larger-smaller) because of padding zeros, because what would you otherwise do if some values get down to zero.

we need to pick which way we want them and adjust the dataset
i would suggest having padding zeros OR `interpolation: none` for measures like earthquakes and tsunamis. Interpolation: none will make bubbles disappear between known values.

@jheeffer what do you think?

**Comment by jheeffer** [comment]
I think the link didn't work well, I updated it. It should show the map with earthquake deaths on GW.

**Comment by jheeffer** [comment]
So 0 on either side of actual data + interpolation -> all countries are always visible with tiny bubble.

2000 0
2001 230
2002 0
2008 0
2009 500
2010 0

etc

**Comment by angieskazka** [comment]
yes, now i get what you mean. we hide bubbles of zero size because it is _outrangeous_. we should instead show tiny bubbles and keep them on screen

**Comment by angieskazka** [comment]
we have it fixed now
