### ISSUE TITLE
Tools page crashes when trying to switch color to 6 region: adds them to state instead of replacing is--world_4region

### ISSUE THREAD

**Issue by dab2000** [vizabi/vizabi#2058]
load bubblechart on tools page http://tools-dev.gapminderdev.org/
change colors to World Regions (6 colors)
reload(F5)

bubbles are OK but color panel is broken

![image](https://cloud.githubusercontent.com/assets/3648190/19420957/d8013542-93f6-11e6-8e1e-3ec5584e1014.png)

console output:
![default](https://cloud.githubusercontent.com/assets/3511460/19219539/26d2fb5e-8e40-11e6-964e-c1a027e5b203.PNG)

**Comment by jheeffer** [comment]
Aha, is--world_6region is saved to URL.
When page is reloaded, URL config is merged with page config.
Since `show` is an object in both, it merges the two without one overwriting the other.

Solutions:
1) External page should do the merging more carefully, using a function which knows about `show` being a modelLeaf with object value. This information is available in https://github.com/vizabi/vizabi/blob/develop/src/models/entities.js#L22 
2) Vizabi could maybe offer such a function for external page to do a merge which takes this into account
