### ISSUE TITLE
Time limits do not return to the broader defaults when switching indicator 

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#2090]
issue #1902 came back after refactoring default time values logic 
here is how Sergey fixed it back then

https://github.com/vizabi/vizabi/pull/1927/commits/d708c80ef18a592db49ace954f49fe10a478161d

**Comment by jheeffer** [comment]
Same bug, different cause.

1. we have default time start/end set to `null`: https://github.com/vizabi/vizabi/blob/develop/src/models/time.js#L35-L36
2. query filter is built using either default or current value: https://github.com/vizabi/vizabi/blob/develop/src/models/time.js#L280
3. But `null` evaluates to false and this time.start/end is always used in query filter while it shouldn't.

Expected behaviour:
Query is built using start/end value which is set by model default/tool default/external config/API but NOT by start/end set by data.

**Comment by angieskazka** [comment]
Suggestion fix #2126
