### ISSUE TITLE
Axis tick text cut off

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2229]
1. Visit http://tools-dev.gapminderdev.org/tools/
2. turn on presentation mode

See the following:

![image](https://cloud.githubusercontent.com/assets/1596071/20762830/073e0246-b728-11e6-8708-5e0ea2fa6be4.png)

**Comment by angieskazka** [comment]
This happens because of the way how label positioning is patched in axis labeler
It is different for two scenarios: when axis redraws immidiately and when it transitions smootly to the new state.

![image](https://user-images.githubusercontent.com/3648190/26871426-5e49d77e-4b73-11e7-921f-24821399b4e6.png)
https://github.com/vizabi/vizabi/blob/develop/src/helpers/d3.axisWithLabelPicker.js#L49-L54

In case of immediate change, the labels are positioned at places by a d3 parent axis class
After that my patches are applied

https://github.com/vizabi/vizabi/blob/develop/src/helpers/d3.axisWithLabelPicker.js#L74-L105
![image](https://user-images.githubusercontent.com/3648190/26871475-9114e662-4b73-11e7-9fad-0d428232f46b.png)

But in case of smooth transition, this code is executed before the transition is complete, and then labels end up in wrong places.

* * *

hence there is a different sequence to reproduce:
1. change the code so that it always executes axis update with transition
2. enable mousewheel zoom in vizabi options->zoom 
3. make labels as big as possible (large presentation mode)
4. Zoom with mouse wheel in and out. If axis does smooth transition you will get this eventually (note labels 45 and 85)

![image](https://user-images.githubusercontent.com/3648190/26871588-0665899e-4b74-11e7-940a-9da746302d4a.png)

* * *
possible solutions

1. best: try to hack it in such a way that labels would transition to their final places. maybe that is impossible because we use labe's final positions to compute later how they should move around from the corners

2. ok: try to apply patching after label transition: factor out the patching thing as a function, attach it to the "end" event of transition

3. these are the ways i could think about. there might be a better solution i don't see

**Comment by angieskazka** [comment]
PR: #2675, commit: https://github.com/vizabi/vizabi/pull/2675/commits/99dbc547535b15b0338149d041f0e30c095c206f

this is ugly because label animates and then jumps, but… i can’t think of anything better yet
