### ISSUE TITLE
The bubbles disappeared from the chart 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2312]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Map

**PLATFORM:** 
* Windows 7  / Google Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools  
2) Click bubble map
3) Click on size 
4) Select For advanced user -> Data Quality (use as color) -> Data Quality-population 
5) Click on Norfolk Island
6) Refresh the page 
7) Refresh the page again

**ACTUAL RESULTS:**
The bubbles disappeared from the chart 

**EXPECTED RESULTS:**
The bubbles should not disappear from the chart 

**SCREENSHOT:**

![12-23-2016 12-30-44 pm](https://cloud.githubusercontent.com/assets/9950837/21449129/da9ed9f4-c90b-11e6-84e7-3b94c95bbb46.jpg)

**Comment by jheeffer** [comment]
Fun effect of url optimization. Works for population too, no need to go to data quality.

1. go to http://tools-stage.gapminderdev.org/tools/#_chart-type=map
2. select norfolk islands (is greyed out but still selectable)

Notice time jumps to 2008 last year that norfolk was available, and norfolk is selected, but neither goes to url.

3. Unselect and select again

Notice now they are in url now: http://tools-stage.gapminderdev.org/tools/#_state_time_value=2008;&entities_select@_geo=nfk;;;;&chart-type=map

4. Refresh

Notice how time value goes out of url: http://tools-stage.gapminderdev.org/tools/#_state_entities_select@_geo=nfk;;;;&chart-type=map
(not sure why)

5. Refresh again

Notice how norfolk select goes out of url:
http://tools-stage.gapminderdev.org/tools/#_state_entities_select@;;;&chart-type=map
(probably because nfk is not visible without time)

**Comment by sergey-filipenko** [comment]
@jheeffer @k6Labz can not reproduce, retest please

**Comment by k6Labz** [comment]
@sergey-filipenko  its not reproducible now

**Comment by angieskazka** [comment]
good 👍
