### ISSUE TITLE
Setting whole state on language update triggers time change event

### ISSUE THREAD

**Issue by kuguarpwnz** [vizabi/vizabi#2450]
history:
`change:time.value` event triggers because we update whole state on language change
and `isSetAllowed` in `model` compares date object with string, so it sets time again
and dispatches `new ChangeEvent`

because of that `onTimeChange` in `barrankchart-component` function calls for `marker.getFrame`
marker model takes `cachePath` which ignores `locale.id` and returns old values. we fixed it, okay!

now we go deeper for `this.getFrames` in `marker` model
it makes `deferredHooks` array and then calls `getFrames` for each of them
in hook we return `this.dataSource.getFrames(this._dataId, steps, selected);`
and here is the problem `getFrames` takes `this._dataId`, but it's outdated.
so we again take old data from `this._collectionPromises[dataId][whatId]["promise"]`

only later `startLoading` will be called and `this._dataId` resets
(`hook` sets it in `loadData().then(afterLoad)`)

main question: how to trigger loading first? or ...?
loading starts after all attributes are set and unfreeze is called (in while loop it executes every freezer)

to reproduce locally:
replace `language` function in `preview/assets/js/_interaction.js` with
```function language(lang) {
  var model = {
    locale: {
      id: lang
    }
  };
  VIZ.setModel(Object.assign({}, VIZABI_MODEL, model));
}
```

so it should be fixed by correct comparison in `isSetAllowed`

**Comment by jheeffer** [comment]
Right, so, the ChangeEvent of time is fired before the new language loading is started. 

This is strange because any change event should be frozen until setting (and any loading resulting from setting) is completely done. During setting also set the locale model, which should trigger a load, which should be finished before the tree is unfrozen.

Why? Because:

locale has dataConnectedChild `id`: 
https://github.com/vizabi/vizabi/blob/develop/src/models/locale.js#L20

Any change to a dataConnectedChild causes loading to start
https://github.com/vizabi/vizabi/blob/develop/src/models/dataconnected.js#L31

This loading is triggered BEFORE the tree could be unfrozen
https://github.com/vizabi/vizabi/blob/develop/src/base/model.js#L201-L215

The unfreezing should NOT happen when there is loading going on
...
but it might already unfreeze... when what you're setting is not a hook:
https://github.com/vizabi/vizabi/blame/develop/src/base/model.js#L209

This line opens up to `freezeCall && !this.isHook() || freezeCall && !this.isLoading()`.

Almost any set which results in loading is on a hook. But now we have a case where it is not. 
Maybe it's enough to remove the isHook() check so we only have `freezeCall && !this.isLoading()`...

But I'm pretty sure the isHook check was there for a reason. 

I can't reproduce now though I think. What error should I see when I add `Object.assign({}, VIZABI_MODEL, model)` to the language function and switch language?

**Comment by kuguarpwnz** [comment]
@jheeffer remove `force` from here https://github.com/vizabi/vizabi/blob/develop/src/tools/barrankchart/barrankchart-component.js#L375

load bar rank chart, change language, see that bar labels are not changed
