### ISSUE TITLE
Optimise all the shadow labels and replace them with mixins

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#2693]
1. Rename `stroke2` to something meaningful, for example, `accent` or `outline`

2. Remove all "shadow" svg text elements, replace them with mixin

vizabi labels helper

vizabi _chart.scss
%vzb-chart-label-shadow and stuff below

bubble chart:
.vzb-bc-label-shadow
.vzb-bc-tooltip-shadow

bubble map
.vzb-bmc-label-shadow
.vzb-shadow

cartogram
.vzb-ct-label-shadow
.vzb-shadow

extapimap
.vzb-shadow
.vzb-bmc-label-shadow
.vzb-label-shadow

![image](https://user-images.githubusercontent.com/3648190/28106844-ca38d8f8-66e5-11e7-9a6c-a467677d7199.png)

**Comment by kuguarpwnz** [comment]
we can try to use this approach instead of copying label every time
https://books.google.com.ua/books?id=ttGqCgAAQBAJ&pg=PA21&lpg=PA21&dq=css+paint-order+alternative&source=bl&ots=J2oTbaGwHX&sig=qzWeCi9xvAsBrakJr1MQK2_tNIg&hl=ru&sa=X&ved=0ahUKEwiQ5Ib97pnVAhUmM5oKHVw9DVwQ6AEISDAE#v=onepage&q=css%20paint-order%20alternative&f=false
