### ISSUE TITLE
Grouping combined with non-fitting show-values in entity disturbs chart

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#780]
Set grouping to 20
Set show to 0-50

Look at disturbed chart

**Comment by angieskazka** [comment]
domain calculation is wrong. it should take into account the min and max requested by the state.
i suggest let's not use show in entities for this purpose
and instead use min-max in marker/axis-y 

what do you say @arthurcamara1

**Comment by jheeffer** [comment]
To me, entities should be used to decide what bars are shown, thus also deciding the domain. The axis_y-model only decides where on the y-axis the bars are shown, in this case in order of age. 

It's debatable if you even want min and max for the y-axis if it's only deciding position like in popbyage, bar or barrank. When the scale is nominal, like countries, definitely not. When the scale is ordinal or higher level, like age, you could but why would you really?
* If you want less bars, limit show. One place to control it is less confusing. 
* If you want more whitespace in your graph... maybe, but why? Also it could be deceiving if there was data for the place where there's now whitespace (but wasn't selected due to entities.show).

**Comment by arthurcamara1** [comment]
I believe the domain of indicators should be in the hook, so the domain for X and Y should be in axis_x and axis_y.

In pop by age it's a more specific case where both the axis and the entities use `age`. So if axis determines 0-80 should be the domain, and entities determine 0-50 should be the entities, I find it completely plausible to see this:

![image](https://cloud.githubusercontent.com/assets/3584238/11186667/fad41174-8c82-11e5-85d9-1b77235eb91f.png)

The only "weird" thing is that grouping by 20 leaves the 40-59 year-olds bar too narrow, when in reality, this group is much bigger.

I don't think the chart is much disturbed. Since we explicitly grouped by 20, *it's still ok*. We should then discuss the following: should the entity domain prevail or the grouping? Should the last bar be shorter in height and show 40-49?

**Comment by angieskazka** [comment]
this looks very old and irrelevant
