### ISSUE TITLE
Differentiate between scale of measurement and scale used for data transformation

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#859]
In metadata.json, the 'scales' for each indicator can be defined. Possible values now are both "ordinal" and "linear" or "log".

This is mixing up [scales of measurement](https://en.wikipedia.org/wiki/Level_of_measurement) like nominal/ratio and different [scales used for data transformation](https://en.wikipedia.org/wiki/Data_transformation_(statistics)) like linear and log.

The former is describes the data, the latter is a choice for how to visualize data. These two should be split in metadata.json or in feature server-implementations.

**Comment by jheeffer** [comment]
Or can we see ordinal and nominal also a scales for transformation?

**Comment by angieskazka** [comment]
Exactly: we only write scales of data representation, but these are connected to the data nature in order to not get absurd visuals

for example: 
the nature of income is logarithmic, this is how psychology works, this is why we should prefer showing income on log scale and use exponential interpolation. Although we may also want to show it as linear.

the nature of life expectancy is linear and we want user to never see logarithmic life expectancy

the nature of population is linear but we can allow user to pick linear or log at their taste

we may also display something that looks totally linear as nominal: number of an athlete in the race, for example. 
we may also display something that looks totally linear as ordinal: place in the race
—these are also examples when we want to describe data in order to manipulate the ways it can be displayed: ordinal and nominal are scales for transformation
